POST https://www.palola.vercel.app/api/startmeal
Content-Type: application/json
Authorization: {{$dotenv ARDUINO_AUTH_KEY}}
{
    "mealName": "lunch"
}

### ====================

GET https://www.palola.vercel.app/api/pendingmeals
Authorization: {{$dotenv ARDUINO_AUTH_KEY}}

### ====================

GET https://www.palola.vercel.app/api/mealgroups
Authorization: {{$dotenv ARDUINO_AUTH_KEY}}

### ====================

POST https://www.palola.vercel.app/api/finishmeal
Content-Type: application/json
Authorization: {{$dotenv ARDUINO_AUTH_KEY}}

{
    "status": 1,
    "id": "6llFdBPxVSXQIfeaxMhJ",
    "weight": 0.450
}
